name: Update LeetCode Stats
on:
  schedule:
    - cron: '0 0 * * *'  # Atualiza todos os dias à meia-noite
  workflow_dispatch:  # Permite rodar manualmente
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update LeetCode stats
        uses: MatheusXavierr/leetcode-profile-readme-action@main
        with:
          username: "MarcoCotas"
          card_theme: "dark"

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Atualizar LeetCode stats" || echo "Nenhuma mudança"
          git push
